/// Files: drivers/net/can/usb/gs_usb.c
/// Fix: fb5be6a7b4863ecc44963bb80ca614584b6c7817
/// Fixes: d08e973a77d128b25e01a08c34d89593fdf222da

virtual detect

@err exists@
identifier rc, urb;
position p;
@@

gs_can_open(...)
{
	...
*	rc = usb_submit_urb(urb, ...);
	if (rc) {
		...
		usb_unanchor_urb(urb);
		... when != usb_free_urb(urb);
*		break;@p
	}
	...
}

@script:python depends on detect@
p << err.p;
@@

coccilib.report.print_report(p[0], 'ERROR: CVE-2019-19052')
